---
- name: CAPX VM Provisioning
  hosts: localhost
  gather_facts: false
  collections:
    - nutanix.ncp
  module_defaults:
    group/nutanix.ncp.ntnx:
      # nutanix_host: "my-pc.thencpnutanix.com"
      # nutanix_username: "admin"
      # nutanix_password: "tmes4EVA!"
      nutanix_host: "10.42.82.39"
      nutanix_username: "admin"
      nutanix_password: ""
      validate_certs: false
  tasks:
    - name: Include vars file
      ansible.builtin.include_vars:
        file: vars.yml
    - name: Create CAPX Image from Source URL
      tags: capx
      nutanix.ncp.ntnx_images:
        state: "present"
        validate_certs: False
        source_uri: "{{ source_uri }}"
        clusters:
          - name: "{{ cluster }}"
        name: "{{ image_name }}"
        image_type: "DISK_IMAGE"
        wait: true
      register: my_image
    - name: Capture image
      tags: image_uuid         # Skip the tag with ansible-playbook create_vm.yml --skip-tags capx,image_uuid
      ansible.builtin.debug:
        msg:
          - "uuid: {{ my_image.image_uuid }}"
          - "name: {{ my_image.response.status.name }}"
    - name: Create a VM with CAPX image
      tags: vm
      nutanix.ncp.ntnx_vms:
        state: present
        name: "{{ vm_name }}"
        timezone: "UTC"
        validate_certs: False
        cluster:
          name: "{{ cluster }}"
        vcpus: 8
        cores_per_vcpu: 1
        memory_gb: 12
        disks:
          - type: "DISK"
            size_gb: 10
            clone_image:
              name: "{{ image_name }}"
            bus: "SCSI"
        guest_customization:
          type: "cloud_init"
          script_path: "./cloud_init.yml"
          is_overridable: True
        networks:
        - is_connected: true
          subnet:
            name: "{{ network_name }}"
      register: vm 
    - ansible.builtin.debug:
        msg:
          - "vm_status: {{ vm.response.status }}"